name: Verify Dependencies Installation

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  test-install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Show installed packages
        run: |
          pip list
